# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "808f090a2f6121e2a7b6279b9413b798"
name = "Conversion Compass App"
type = "custom"
application_url = "https://backend.shopconversionhistory.com/index.php"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_draft_orders,read_merchant_managed_fulfillment_orders,read_order_edits,read_orders,read_third_party_fulfillment_orders,customer_read_draft_orders,customer_read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://backend.shopconversionhistory.com/auth/callback.php"
]


[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://backend.shopconversionhistory.com/webhooks/compliance.php"
